//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationDataServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportingEntities : DbContext
    {
        public ReportingEntities()
            : base("name=ReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<QuestionResult> QuestionResults { get; set; }
    }
}
