//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public string full_describe { get; set; }
        public string person_name { get; set; }
        public string service_name { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string client_name { get; set; }
        public string client_email { get; set; }
        public string client_phone { get; set; }
        public string client_mobile { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<bool> on_waitlist { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<bool> attended { get; set; }
        public Nullable<System.DateTime> booking_updated { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> person_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> paid { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<bool> is_cancelled { get; set; }
        public string channel { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> event_id { get; set; }
        public string event_title { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
