//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> duration { get; set; }
        public string group { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string long_description { get; set; }
        public Nullable<int> capacity_view { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> spaces { get; set; }
        public string person_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> max_num_bookings { get; set; }
        public Nullable<System.DateTime> min_advance_time { get; set; }
        public string ticket_type { get; set; }
        public Nullable<bool> email_per_ticket { get; set; }
        public Nullable<bool> questions_per_ticket { get; set; }
        public Nullable<bool> course { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
